module.exports = [
    {
      "id": 482,
      "appId": 2,
      "name": "Progressive Web Experience",
      "firstDay": "2019-12-01T00:00:00",
      "lastDay": "2019-12-04T23:59:59",
      "year": 2019,
      "abreviation": "RWX2019",
      "location": {
        "description": "Opal Sands Resort",
        "address1": "430 South Gulfview Blvd",
        "address2": null,
        "city": "Clearwater",
        "metro": "Clearwater",
        "stateCode": "FL",
        "otherState": null,
        "countryCode": null,
        "zip": "33767",
        "altMapLink": "",
        "latitude": 27.9696455,
        "longitude": -82.8300824,
        "utcOffset": -5,
        "timeZoneName": "America/New_York",
        "stateCodeDisplay": "FL",
        "mapLink": "http://maps.google.com/maps?q=430+South+Gulfview+Blvd,+Clearwater,+FL+33767&hl=en",
        "googleMapLink": "http://maps.google.com/maps?q=430+South+Gulfview+Blvd,+Clearwater,+FL+33767&hl=en",
        "metroArea": "Clearwater, FL",
        "state": "Florida",
        "country": null
      },
      "cacheDir": "clearwater/2019/12",
      "permaLink": "",
      "flickrPhotosetId": null,
      "speakerSort": 0,
      "publishRegistration": true,
      "publishSessions": true,
      "publishAgenda": true,
      "roomsAssigned": true,
      "publishSlides": true,
      "publishVideo": null,
      "publishAudio": false,
      "canceled": false,
      "modified": "2019-11-23T22:47:08",
      "masterId": 48,
      "regServiceId": 3,
      "latitude": 27.9696455,
      "longitude": -82.8300824,
      "dayCount": 4,
      "refundCutoff": "2019-10-20T00:00:00",
      "dates": "December 1 - 4, 2019",
      "mediumDates": "Dec 1 - 4, 2019",
      "shortDates": "Dec 1 - 4",
      "isPast": false,
      "hotelImagePath": "/s/images/travelinfo/482_1552874543225_hotel.jpg",
      "urlBase": "",
      "displayUrl": "https://progressivewebexperience.io/conference/clearwater/2019/12/home"
    },
    {
      "id": 479,
      "appId": 19,
      "name": "TechLeader Summit",
      "firstDay": "2019-12-04T00:00:00",
      "lastDay": "2019-12-06T23:59:59",
      "year": 2019,
      "abreviation": "TLS2019",
      "location": {
        "description": "Opal Sands Resort",
        "address1": "430 South Gulfview Blvd",
        "address2": null,
        "city": "Clearwater",
        "metro": "Clearwater",
        "stateCode": "FL",
        "otherState": null,
        "countryCode": null,
        "zip": "33767",
        "altMapLink": "",
        "latitude": 27.9697078,
        "longitude": -82.8301494,
        "utcOffset": -5,
        "timeZoneName": "America/New_York",
        "stateCodeDisplay": "FL",
        "mapLink": "http://maps.google.com/maps?q=430+South+Gulfview+Blvd,+Clearwater,+FL+33767&hl=en",
        "googleMapLink": "http://maps.google.com/maps?q=430+South+Gulfview+Blvd,+Clearwater,+FL+33767&hl=en",
        "metroArea": "Clearwater, FL",
        "state": "Florida",
        "country": null
      },
      "cacheDir": "clearwater/2019/12",
      "permaLink": "",
      "flickrPhotosetId": null,
      "speakerSort": 0,
      "publishRegistration": true,
      "publishSessions": true,
      "publishAgenda": true,
      "roomsAssigned": true,
      "publishSlides": true,
      "publishVideo": null,
      "publishAudio": false,
      "canceled": false,
      "modified": "2019-11-21T14:19:48",
      "masterId": 88,
      "regServiceId": 3,
      "latitude": 27.9697078,
      "longitude": -82.8301494,
      "dayCount": 3,
      "refundCutoff": "2019-10-23T00:00:00",
      "dates": "December 4 - 6, 2019",
      "mediumDates": "Dec 4 - 6, 2019",
      "shortDates": "Dec 4 - 6",
      "isPast": false,
      "hotelImagePath": "/s/images/travelinfo/479_1545258394525_hotel.jpg",
      "urlBase": "",
      "displayUrl": "https://techleadersummit.io/conference/clearwater/2019/12/home"
    },
    {
      "id": 481,
      "appId": 13,
      "name": "ArchConf",
      "firstDay": "2019-12-09T00:00:00",
      "lastDay": "2019-12-12T23:59:59",
      "year": 2019,
      "abreviation": "ARCH",
      "location": {
        "description": "Opal Sands Resort",
        "address1": "430 South Gulfview Blvd",
        "address2": null,
        "city": "Clearwater",
        "metro": "Clearwater",
        "stateCode": "FL",
        "otherState": null,
        "countryCode": null,
        "zip": "33767",
        "altMapLink": "",
        "latitude": 27.9696455,
        "longitude": -82.8300824,
        "utcOffset": -5,
        "timeZoneName": "America/New_York",
        "stateCodeDisplay": "FL",
        "mapLink": "http://maps.google.com/maps?q=430+South+Gulfview+Blvd,+Clearwater,+FL+33767&hl=en",
        "googleMapLink": "http://maps.google.com/maps?q=430+South+Gulfview+Blvd,+Clearwater,+FL+33767&hl=en",
        "metroArea": "Clearwater, FL",
        "state": "Florida",
        "country": null
      },
      "cacheDir": "clearwater/2019/12",
      "permaLink": "",
      "flickrPhotosetId": null,
      "speakerSort": 0,
      "publishRegistration": true,
      "publishSessions": true,
      "publishAgenda": true,
      "roomsAssigned": true,
      "publishSlides": true,
      "publishVideo": null,
      "publishAudio": false,
      "canceled": false,
      "modified": "2019-11-25T11:29:18",
      "masterId": 82,
      "regServiceId": 3,
      "latitude": 27.9696455,
      "longitude": -82.8300824,
      "dayCount": 4,
      "refundCutoff": "2019-10-28T00:00:00",
      "dates": "December 9 - 12, 2019",
      "mediumDates": "Dec 9 - 12, 2019",
      "shortDates": "Dec 9 - 12",
      "isPast": false,
      "hotelImagePath": "/s/images/travelinfo/481_1549036020916_hotel.jpg",
      "urlBase": "",
      "displayUrl": "https://archconf.com/conference/clearwater/2019/12/home"
    },
    {
      "id": 483,
      "appId": 1,
      "name": "Greater Wisconsin Software Symposium",
      "firstDay": "2020-02-21T00:00:00",
      "lastDay": "2020-02-22T23:59:59",
      "year": 2020,
      "abreviation": "GWSS2020",
      "location": {
        "description": "Sheraton Madison",
        "address1": "706 John Nolen Drive",
        "address2": null,
        "city": "Madison",
        "metro": "Madison",
        "stateCode": "WI",
        "otherState": null,
        "countryCode": null,
        "zip": "53713",
        "altMapLink": "",
        "latitude": 43.0474951,
        "longitude": -89.3732083,
        "utcOffset": -6,
        "timeZoneName": "America/Chicago",
        "stateCodeDisplay": "WI",
        "mapLink": "http://maps.google.com/maps?q=706+John+Nolen+Drive,+Madison,+WI+53713&hl=en",
        "googleMapLink": "http://maps.google.com/maps?q=706+John+Nolen+Drive,+Madison,+WI+53713&hl=en",
        "metroArea": "Madison, WI",
        "state": "Wisconsin",
        "country": null
      },
      "cacheDir": "madison/2020/02",
      "permaLink": "madison",
      "flickrPhotosetId": null,
      "speakerSort": 0,
      "publishRegistration": true,
      "publishSessions": false,
      "publishAgenda": false,
      "roomsAssigned": false,
      "publishSlides": false,
      "publishVideo": null,
      "publishAudio": false,
      "canceled": false,
      "modified": "2019-11-22T14:41:42",
      "masterId": 20,
      "regServiceId": 3,
      "latitude": 43.0474951,
      "longitude": -89.3732083,
      "dayCount": 2,
      "refundCutoff": "2020-01-10T00:00:00",
      "dates": "February 21 - 22, 2020",
      "mediumDates": "Feb 21 - 22, 2020",
      "shortDates": "Feb 21 - 22",
      "isPast": false,
      "hotelImagePath": "/s/images/travelinfo/483_1564513152605_hotel.jpg",
      "urlBase": "/madison",
      "displayUrl": "/madison"
    },
    {
      "id": 484,
      "appId": 1,
      "name": "Salt Lake Software Symposium",
      "firstDay": "2020-02-28T00:00:00",
      "lastDay": "2020-02-29T23:59:59",
      "year": 2020,
      "abreviation": "SLSS",
      "location": {
        "description": "Radisson Salt Lake City Hotel",
        "address1": "215 West South Temple",
        "address2": null,
        "city": "Salt Lake City",
        "metro": "Salt Lake City",
        "stateCode": "UT",
        "otherState": null,
        "countryCode": null,
        "zip": "84101",
        "altMapLink": "",
        "latitude": 40.7689137,
        "longitude": -111.8974773,
        "utcOffset": -7,
        "timeZoneName": "America/Denver",
        "stateCodeDisplay": "UT",
        "mapLink": "http://maps.google.com/maps?q=215+West+South+Temple,+Salt+Lake+City,+UT+84101&hl=en",
        "googleMapLink": "http://maps.google.com/maps?q=215+West+South+Temple,+Salt+Lake+City,+UT+84101&hl=en",
        "metroArea": "Salt Lake City, UT",
        "state": "Utah",
        "country": null
      },
      "cacheDir": "salt_lake_city/2020/02",
      "permaLink": "saltlakecity",
      "flickrPhotosetId": null,
      "speakerSort": 0,
      "publishRegistration": true,
      "publishSessions": false,
      "publishAgenda": false,
      "roomsAssigned": false,
      "publishSlides": false,
      "publishVideo": null,
      "publishAudio": false,
      "canceled": false,
      "modified": "2019-11-15T16:14:34",
      "masterId": 1,
      "regServiceId": 3,
      "latitude": 40.7689137,
      "longitude": -111.8974773,
      "dayCount": 2,
      "refundCutoff": "2020-01-17T00:00:00",
      "dates": "February 28 - 29, 2020",
      "mediumDates": "Feb 28 - 29, 2020",
      "shortDates": "Feb 28 - 29",
      "isPast": false,
      "hotelImagePath": "/s/images/travelinfo/484_1564513180051_hotel.jpg",
      "urlBase": "/saltlakecity",
      "displayUrl": "/saltlakecity"
    },
    {
      "id": 489,
      "appId": 1,
      "name": "Twin Cities Software Symposium",
      "firstDay": "2020-03-06T00:00:00",
      "lastDay": "2020-03-08T23:59:59",
      "year": 2020,
      "abreviation": "TCSS2020SE",
      "location": {
        "description": "Hilton Minneapolis/Bloomington Hotel",
        "address1": "3900 American Boulevard West",
        "address2": null,
        "city": "Bloomington",
        "metro": "Minneapolis",
        "stateCode": "MN",
        "otherState": null,
        "countryCode": null,
        "zip": "55437",
        "altMapLink": "",
        "latitude": 44.8564039,
        "longitude": -93.3303528,
        "utcOffset": -6,
        "timeZoneName": "America/Chicago",
        "stateCodeDisplay": "MN",
        "mapLink": "http://maps.google.com/maps?q=3900+American+Boulevard+West,+Bloomington,+MN+55437&hl=en",
        "googleMapLink": "http://maps.google.com/maps?q=3900+American+Boulevard+West,+Bloomington,+MN+55437&hl=en",
        "metroArea": "Minneapolis, MN",
        "state": "Minnesota",
        "country": null
      },
      "cacheDir": "minneapolis/2020/03",
      "permaLink": "minneapolis",
      "flickrPhotosetId": null,
      "speakerSort": 0,
      "publishRegistration": true,
      "publishSessions": false,
      "publishAgenda": false,
      "roomsAssigned": false,
      "publishSlides": false,
      "publishVideo": null,
      "publishAudio": null,
      "canceled": false,
      "modified": "2019-11-16T15:40:16",
      "masterId": 7,
      "regServiceId": 3,
      "latitude": 44.8564039,
      "longitude": -93.3303528,
      "dayCount": 3,
      "refundCutoff": "2020-01-24T00:00:00",
      "dates": "March 6 - 8, 2020",
      "mediumDates": "Mar 6 - 8, 2020",
      "shortDates": "Mar 6 - 8",
      "isPast": false,
      "hotelImagePath": "/s/images/travelinfo/489_1568749696592_hotel.jpg",
      "urlBase": "/minneapolis",
      "displayUrl": "/minneapolis"
    },
    {
      "id": 490,
      "appId": 1,
      "name": "New England Software Symposium",
      "firstDay": "2020-03-13T00:00:00",
      "lastDay": "2020-03-15T23:59:59",
      "year": 2020,
      "abreviation": "NESS2020SE",
      "location": {
        "description": "Four Points by Sheraton",
        "address1": "1 Audubon Road",
        "address2": null,
        "city": "Wakefield",
        "metro": "Boston",
        "stateCode": "MA",
        "otherState": null,
        "countryCode": null,
        "zip": "01880",
        "altMapLink": "",
        "latitude": 42.5141693,
        "longitude": -71.0398307,
        "utcOffset": -5,
        "timeZoneName": "America/New_York",
        "stateCodeDisplay": "MA",
        "mapLink": "http://maps.google.com/maps?q=1+Audubon+Road,+Wakefield,+MA+01880&hl=en",
        "googleMapLink": "http://maps.google.com/maps?q=1+Audubon+Road,+Wakefield,+MA+01880&hl=en",
        "metroArea": "Boston, MA",
        "state": "Massachusetts",
        "country": null
      },
      "cacheDir": "boston/2020/03",
      "permaLink": "boston",
      "flickrPhotosetId": null,
      "speakerSort": 0,
      "publishRegistration": true,
      "publishSessions": false,
      "publishAgenda": false,
      "roomsAssigned": false,
      "publishSlides": false,
      "publishVideo": null,
      "publishAudio": null,
      "canceled": false,
      "modified": "2019-09-17T15:48:49",
      "masterId": 6,
      "regServiceId": 3,
      "latitude": 42.5141693,
      "longitude": -71.0398307,
      "dayCount": 3,
      "refundCutoff": "2020-01-31T00:00:00",
      "dates": "March 13 - 15, 2020",
      "mediumDates": "Mar 13 - 15, 2020",
      "shortDates": "Mar 13 - 15",
      "isPast": false,
      "hotelImagePath": "/s/images/travelinfo/490_1568749729471_hotel.jpg",
      "urlBase": "/boston",
      "displayUrl": "/boston"
    },
    {
      "id": 485,
      "appId": 1,
      "name": "Gateway Software Symposium",
      "firstDay": "2020-04-03T00:00:00",
      "lastDay": "2020-04-04T23:59:59",
      "year": 2020,
      "abreviation": "GSS2020",
      "location": {
        "description": "St. Louis Marriott West",
        "address1": "660 Maryville Centre Drive",
        "address2": null,
        "city": "St. Louis",
        "metro": "St. Louis",
        "stateCode": "MO",
        "otherState": null,
        "countryCode": null,
        "zip": "63141",
        "altMapLink": "",
        "latitude": 38.6421032,
        "longitude": -90.4966399,
        "utcOffset": -6,
        "timeZoneName": "America/Chicago",
        "stateCodeDisplay": "MO",
        "mapLink": "http://maps.google.com/maps?q=660+Maryville+Centre+Drive,+St.+Louis,+MO+63141&hl=en",
        "googleMapLink": "http://maps.google.com/maps?q=660+Maryville+Centre+Drive,+St.+Louis,+MO+63141&hl=en",
        "metroArea": "St. Louis, MO",
        "state": "Missouri",
        "country": null
      },
      "cacheDir": "st_louis/2020/04",
      "permaLink": "stlouis",
      "flickrPhotosetId": null,
      "speakerSort": 0,
      "publishRegistration": true,
      "publishSessions": false,
      "publishAgenda": false,
      "roomsAssigned": false,
      "publishSlides": false,
      "publishVideo": null,
      "publishAudio": null,
      "canceled": false,
      "modified": "2019-08-02T16:39:33",
      "masterId": 21,
      "regServiceId": 3,
      "latitude": 38.6421032,
      "longitude": -90.4966399,
      "dayCount": 2,
      "refundCutoff": "2020-02-21T00:00:00",
      "dates": "April 3 - 4, 2020",
      "mediumDates": "Apr 3 - 4, 2020",
      "shortDates": "Apr 3 - 4",
      "isPast": false,
      "hotelImagePath": "/s/images/travelinfo/485_1564778373238_hotel.jpg",
      "urlBase": "/stlouis",
      "displayUrl": "/stlouis"
    }
];
