= No-Fluff/Just-Stuff Alexa Skill

This repository contains the code for a NodeJS-based Alexa skill for querying about upcoming https://nofluffjuststuff.com[No-Fluff/Just-Stuff] events.

Once deployed, you can open the skill and ask things such as the following:

 - "Alexa, open No Fluff Just Stuff"
 - "When is the next event?"
 - "Tell me about the next 5 events." (not yet implemented)
 - "Who is presenting at the Chicago show?" (not yet implemented)
 - "What talks is Craig Walls giving in Minneapolis?" (not yet implemented)

== Deploying

This project includes a skill.json file, enabling deployment using the https://developer.amazon.com/docs/smapi/ask-cli-intro.html#alexa-skills-kit-command-line-interface-ask-cli[ASK CLI].

Assuming that you have the ASK CLI installed and have already performed `ask init` to authentication the CLI with your Amazon account, you can deploy the skill by issuing `ask deploy` from within the root directory of the project.

== Testing

If you have Bespoken's BST Tools installed, you can run automated tests (even offline)
like this:

```
$ bst test
```

== Motivation

I had several motivations for developing this skill:

 - I wanted a richer, more real-world example skill for demo and presentation purposes. Using the NFJS domain seemed like a natural choice as I hope to be presenting this topic frequently on the NFJS tour.
 - I wanted a chance to try out the NodeJS implementation of the new ASK SDK v2, released in early 2018.
 - (Full honesty) Amazon sent out an invitation to developers who had already published a skill prior to Sept 30, 2018 to publish another skill and receive a new Echo Show. Having an Echo Show in my collection will enable me to more deeply explore developing voice applications that have a visual component. And it's hard to turn down free hardware.

Given my interest in developing Alexa skills with Spring (see https://github.com/habuma/spring-skills[Spring Skills]), you might wonder why I chose to develop this in Node. Ny reasons for choosing Node over Java and Spring are as follows:

 - As mentioned above, I was eager to try out the newest Node SDK.
 - Java-based functions deployed to AWS Lambda have an unfortunate cold-start delay that results in a delayed response from Alexa if the skill hasn't been used lately.
 - I could have deployed a Spring Skills-based implementation elsewhere (such as https://run.pivotal.io/[Pivotal Web Services]) to overcome the cold-start issue, but in the interest of obtaining a free Echo Show (again, I offer full-disclosure in this matter), I didn't want to raise any questions about why the skill isn't deployed in AWS Lambda.
 - I do intend to reimplement this skill with Spring Skills at a later time, for comparison's sake and as a richer, more real-world example of a skill based on Spring Skills that can respond to both Alexa and Google Assistant requests. (Stay tuned)
